### ISSUE TITLE
ManniBot not working

### ISSUE THREAD

**Issue by oneserv-heuser** [freakyblue/DVBManniBot#14]
Hey!

Since a few days the ManniBot stopped working. I don't get answer from it anymore, same for other people I asked. Could you have a look into it?

**Comment by oneserv-heuser** [comment]
@freakyblue I can narrow it down a bit now, it doesn't apply to all stops. Some stops work, some don't.

For example the Grillparzerstrasse (GRI) doesn't work, there is no answer from the bot.
ElbePark (EPK) and Pirnaischer Platz (PIP) are working for example.

Some other not working examples: Overbeckstrasse (OVE), Schlehenstrasse (SLE).

Also if you type a name that offers several possibilities there is only an empty answer with "Meinten Sie?" and no choices.

Hope this helps.

**Comment by freakyblue** [comment]
@oneserv-heuser thanks for the issue report. i hope it's fixed now.

**Comment by t-heuser** [comment]
@freakyblue Thanks, it's working again.
